package Default;


import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author Claudia
 */
public class InterfataCasa extends javax.swing.JFrame {

    /**
     * Creates new form InterfataCasa
     */
    public InterfataCasa() {
        initComponents();
        creazaLista();
    }
   
    double kg;
    double subTotal = 0;
    int CodNumar; 
    int counter = 0; // numara de cate ori este incasat un produs
    
    public void creazaLista(){ // lista de produse afisat in frame!
        DefaultListModel model = new DefaultListModel();
        Produs[] produse = declaraObiecte();
        // array-ul de produse
        for(int k = 0 ; k < produse.length; k++){
            String hope = getNumeProdus(k);
            model.addElement(hope);
        }
       jList1.setModel(model);
     
}
    public Produs[] declaraObiecte(){
        Produs [] produse = new Produs[7];
        produse[0] = new Produs(4058, 1.00, "Bagheta Paine", true); 
        produse[1] = new Produs(3500, 5.00, "Banane KG", false);
        produse[2] = new Produs(4825, 0.89, "Chifla", true);
        produse[3] = new Produs(1234, 4.00, "Avocado", true);
        produse[4] = new Produs(1752, 2.50, "Cartofi KG", false);
        produse[5] = new Produs(1716, 2.00, "Ceapa Plasa", true);
        produse[6] = new Produs(4770, 3.49, "Gogoasa Zahar", true);
        return produse;
    }
      
    public String getNumeProdus(int i){
        Produs[] produse = declaraObiecte();
        String nume = produse[i].getNume();
        
        return nume;
    }
    
  
    public String cautaObiecte(int cod, String ceCaut){
        
    Produs[] produse = declaraObiecte();
    
    String produsGasit = null;  // returneaza "atributul" produsului in functie de paraemtrul ceCaut
        switch (ceCaut) {
            case "Nume":
                for (Produs produse1 : produse) {
                    if (produse1.getCod() == cod) {
                        produsGasit = produse1.getNume();                    
                    }
                }       break;
            case "Pret":
                for (Produs produse1 : produse) {
                    if (produse1.getCod() == cod) {
                        double Pret = produse1.getPret();
                        produsGasit = String.format("%.02f", Pret);
                    }
                }       break;
            case "Boolean":
                for (Produs produse1 : produse) {
                    if (produse1.getCod() == cod) {
                        if (!produse1.esteBuc) {
                            produsGasit = "false";
                        } else {
                            produsGasit = "true";
                        }
                    }
                }       break;            
        }
    return produsGasit;
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jDialog5 = new javax.swing.JDialog();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jDialog6 = new javax.swing.JDialog();
        TextIntrodus = new javax.swing.JTextField();
        LNume = new javax.swing.JTextField();
        LCost = new javax.swing.JTextField();
        LButton1 = new javax.swing.JButton();
        LButton2 = new javax.swing.JButton();
        LButton3 = new javax.swing.JButton();
        LButton4 = new javax.swing.JButton();
        LButton5 = new javax.swing.JButton();
        LButton6 = new javax.swing.JButton();
        LButton7 = new javax.swing.JButton();
        LButton8 = new javax.swing.JButton();
        LButton9 = new javax.swing.JButton();
        LButtonInput = new javax.swing.JButton();
        LButton0 = new javax.swing.JButton();
        LButton00 = new javax.swing.JButton();
        LTotalButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        LClear = new javax.swing.JButton();
        LSubtotal = new javax.swing.JTextField();
        LButtonVir = new javax.swing.JButton();
        LButtonINM = new javax.swing.JButton();
        LX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qw = new javax.swing.JLabel();
        we = new javax.swing.JLabel();
        er = new javax.swing.JLabel();
        rTotal = new javax.swing.JTextField();
        rNumerar = new javax.swing.JTextField();
        rRest = new javax.swing.JTextField();
        R6 = new javax.swing.JButton();
        R7 = new javax.swing.JButton();
        R8 = new javax.swing.JButton();
        R9 = new javax.swing.JButton();
        R0 = new javax.swing.JButton();
        R00 = new javax.swing.JButton();
        R1 = new javax.swing.JButton();
        R2 = new javax.swing.JButton();
        R3 = new javax.swing.JButton();
        R4 = new javax.swing.JButton();
        R5 = new javax.swing.JButton();
        rIncaseaza = new javax.swing.JButton();
        R10lei = new javax.swing.JButton();
        R1Leu = new javax.swing.JButton();
        R50lei = new javax.swing.JButton();
        rC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        adauga = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 450));
        setSize(new java.awt.Dimension(1200, 450));

        TextIntrodus.setEditable(false);

        LNume.setEditable(false);
        LNume.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N

        LCost.setEditable(false);
        LCost.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N

        LButton1.setText("1");
        LButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton1ActionPerformed(evt);
            }
        });

        LButton2.setText("2");
        LButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton2ActionPerformed(evt);
            }
        });

        LButton3.setText("3");
        LButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton3ActionPerformed(evt);
            }
        });

        LButton4.setText("4");
        LButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton4ActionPerformed(evt);
            }
        });

        LButton5.setText("5");
        LButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton5ActionPerformed(evt);
            }
        });

        LButton6.setText("6");
        LButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton6ActionPerformed(evt);
            }
        });

        LButton7.setText("7");
        LButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton7ActionPerformed(evt);
            }
        });

        LButton8.setText("8");
        LButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton8ActionPerformed(evt);
            }
        });

        LButton9.setText("9");
        LButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton9ActionPerformed(evt);
            }
        });

        LButtonInput.setText("Inp");
        LButtonInput.setToolTipText("");
        LButtonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonInputActionPerformed(evt);
            }
        });

        LButton0.setText("0");
        LButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton0ActionPerformed(evt);
            }
        });

        LButton00.setText("00");
        LButton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButton00ActionPerformed(evt);
            }
        });

        LTotalButton.setText("TOTAL");
        LTotalButton.setMaximumSize(new java.awt.Dimension(79, 79));
        LTotalButton.setPreferredSize(new java.awt.Dimension(79, 50));
        LTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTotalButtonActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 10));

        LClear.setText("Clear");
        LClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LClearActionPerformed(evt);
            }
        });

        LSubtotal.setEditable(false);
        LSubtotal.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N

        LButtonVir.setText(".");
        LButtonVir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonVirActionPerformed(evt);
            }
        });

        LButtonINM.setText("*");
        LButtonINM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonINMActionPerformed(evt);
            }
        });

        LX.setText("X");
        LX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LXActionPerformed(evt);
            }
        });

        jLabel1.setText("Produs");

        jLabel2.setText("Pret");

        jLabel3.setText("STotal");

        qw.setText("TOTAL");

        we.setText("Numerar");

        er.setText("Rest");

        rTotal.setEditable(false);
        rTotal.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        rTotal.setPreferredSize(new java.awt.Dimension(9, 22));

        rNumerar.setEditable(false);
        rNumerar.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N

        rRest.setEditable(false);
        rRest.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N

        R6.setText("6");
        R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R6ActionPerformed(evt);
            }
        });

        R7.setText("7");
        R7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R7ActionPerformed(evt);
            }
        });

        R8.setText("8");
        R8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R8ActionPerformed(evt);
            }
        });

        R9.setText("9");
        R9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R9ActionPerformed(evt);
            }
        });

        R0.setText("0");
        R0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R0ActionPerformed(evt);
            }
        });

        R00.setText("00");
        R00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R00ActionPerformed(evt);
            }
        });

        R1.setText("1");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });

        R2.setText("2");
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });

        R3.setText("3");
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });

        R4.setText("4");
        R4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R4ActionPerformed(evt);
            }
        });

        R5.setText("5");
        R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5ActionPerformed(evt);
            }
        });

        rIncaseaza.setText("Numerar");
        rIncaseaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIncaseazaActionPerformed(evt);
            }
        });

        R10lei.setText("10.00");
        R10lei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R10leiActionPerformed(evt);
            }
        });

        R1Leu.setText("1.00");
        R1Leu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1LeuActionPerformed(evt);
            }
        });

        R50lei.setText("50.00");
        R50lei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R50leiActionPerformed(evt);
            }
        });

        rC.setText("C");
        rC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCActionPerformed(evt);
            }
        });

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produs", "Pret"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jScrollPane2.setViewportView(jList1);

        adauga.setText("Adauga");
        adauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(adauga)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(TextIntrodus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LButtonVir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LButtonINM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(LButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LButtonInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(LButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LClear))))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rRest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(R10lei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(R1Leu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(R50lei, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(R0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(R00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rIncaseaza, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LCost, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(LNume, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qw)
                                    .addComponent(we))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rNumerar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(er))
                                    .addComponent(rTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LButtonInput, LClear, LTotalButton, TextIntrodus});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LCost, LSubtotal, rNumerar, rRest});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {er, jLabel2, jLabel3, we});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qw))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rNumerar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(we))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rRest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(er)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(R1Leu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(R50lei, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(R10lei, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(R00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rIncaseaza, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LNume, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(LSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LClear)
                                .addComponent(LX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButtonInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextIntrodus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButton00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButtonVir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LButtonINM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adauga)))
                .addGap(94, 94, 94)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LButton0, LButton00, LButton1, LButton2, LButton3, LButton4, LButton5, LButton6, LButton7, LButton8, LButton9, LButtonInput, LClear});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LCost, LNume, LSubtotal, LTotalButton, TextIntrodus, rNumerar, rRest});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {er, jLabel2, jLabel3, we});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void LButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton2ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton2.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton2ActionPerformed
    
    public void adaugaProduskg(){
        String produsVer = cautaObiecte(CodNumar, "Nume");  
        LNume.setText(kg + " x " + produsVer);
            
        String Pret = cautaObiecte(CodNumar, "Pret"); // pretul gasit din metoda(sau din obiect)
        double pret = Double.parseDouble(Pret);  // transforma pretul din obiect in double pentru a inmulti cu kilogramul introdus anterior
        double PretAfisat = kg * pret;  
        Pret = Double.toString(PretAfisat); // conversie inapoi la String pentru a fi afisat in box
        Pret = String.format("%.02f", PretAfisat);
        LCost.setText(Pret);
                
        subTotal += PretAfisat;
        String SubTotal = Double.toString(subTotal);
        SubTotal = String.format("%.02f", subTotal); 
        LSubtotal.setText(SubTotal);
                
        adaugaLista(produsVer, Pret);
        kg = 0;
    }  
    
    public void adaugaProdus(){
        counter = 0;
        String produsVer = cautaObiecte(CodNumar, "Nume");
        counter++;
        LNume.setText(counter +"x "+ produsVer);
        
        String Pret = cautaObiecte(CodNumar, "Pret");
        double pret = Double.parseDouble(Pret); // folosit mai tarziu pentru afisaj subtotal
        LCost.setText(Pret);
        
        subTotal += pret;
        String SubTotal = Double.toString(subTotal);
        SubTotal = String.format("%.02f", subTotal); 
        LSubtotal.setText(SubTotal);

        adaugaLista(produsVer, Pret);  
    }
    private void LButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonInputActionPerformed
        rRest.setText(null);
        if(TextIntrodus.getText().equals("")){ // verifica daca s-a tastat cv in TextIntrodus
            eroare("Niciun cod valid introdus.");
            return;
        }
        String codIntrodus = TextIntrodus.getText();
        if (!codIntrodus.contains("."))
            CodNumar = Integer.parseInt(codIntrodus);
        else { 
            eroare("Codul nu este valabil");
            TextIntrodus.setText(null);
            return;         
        }
        if (CodNumar > 9999 || CodNumar < 999){ // verifica daca CodProdus este valabil
            eroare("Codul nu este valabil.");
            TextIntrodus.setText(null);
            return;
        }
        
       String gasit = cautaObiecte(CodNumar,"Nume");
       if(gasit == null){
          eroare("Codul nu este valabil.");
          TextIntrodus.setText(null); 
          return;
       }       
        
        if(kg != 0){
            if(cautaObiecte(CodNumar,"Boolean").equals("false")){ // verifica daca produsul are atributul de produs la kilogram
                adaugaProduskg();
            } else { 
                eroare("Produsul este la bucata.");
            }   
        } else if (cautaObiecte(CodNumar,"Boolean").equals("true")){ // conditia de produs la bucata 
            adaugaProdus();
        } else   // conditie de produs la kilogram introdus fara prefixul de kilogram
            eroare("Produsul este la kilogram.");             
        TextIntrodus.setText(null);
        
    }//GEN-LAST:event_LButtonInputActionPerformed

    public void adaugaLista(String nume, String pret){
        DefaultTableModel model = (DefaultTableModel) Tabel.getModel(); 
        if(!nume.equals("delete")){
            model.addRow(new Object[]{nume,pret});
       } else { 
             int rowCount = model.getRowCount();
             for(int i = rowCount - 1; i >= 0 ; i--){
                 model.removeRow(i);
            }
        }       
}
 
    public void eroare(String error){
            JTextArea outputArea = new JTextArea(16,10);
            outputArea.setText(error);
            JOptionPane.showMessageDialog(null, error, "!", JOptionPane.ERROR_MESSAGE);
    }
    
    // urmatoarea bucata de cod transmite cifrele in textbox( partea de incasare produse)
    
    private void LButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton0ActionPerformed
        // TODO add your handling code here:
        String EnterNumber  = TextIntrodus.getText() + LButton0.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton0ActionPerformed

    private void LButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton1ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton1.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton1ActionPerformed

    private void LButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton4ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton4.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton4ActionPerformed

    private void LButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton5ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton5.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton5ActionPerformed

    private void LButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton6ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton6.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton6ActionPerformed

    private void LButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton7ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton7.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton7ActionPerformed

    private void LButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton8ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton8.getText();
        TextIntrodus.setText(EnterNumber);        
    }//GEN-LAST:event_LButton8ActionPerformed

    private void LButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton9ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton9.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton9ActionPerformed

    private void LButton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton00ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton00.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton00ActionPerformed

    private void LButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButton3ActionPerformed
        String EnterNumber  = TextIntrodus.getText() + LButton3.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButton3ActionPerformed

    private void LClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LClearActionPerformed
        TextIntrodus.setText(null);
        kg = 0;
    }//GEN-LAST:event_LClearActionPerformed

    private void LButtonVirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonVirActionPerformed
        String EnterNumber = TextIntrodus.getText() + LButtonVir.getText();
        TextIntrodus.setText(EnterNumber);
    }//GEN-LAST:event_LButtonVirActionPerformed

    private void LButtonINMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonINMActionPerformed
            if (!TextIntrodus.getText().equals("")){
                String EnterNumber = TextIntrodus.getText(); // pastreaza kilogramele
                kg = Double.parseDouble(EnterNumber); 
                TextIntrodus.setText(null);
            } else {
                eroare("Cantitate invalida.");
            }         
    }//GEN-LAST:event_LButtonINMActionPerformed

    private void LXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LXActionPerformed
        String gasit = cautaObiecte(CodNumar,"Nume");
            if(gasit == null){
                eroare("Codul nu este valabil.");
                TextIntrodus.setText(null); 
                return;
       }
        if (CodNumar != 0){          
            if(cautaObiecte(CodNumar,"Boolean").equals("true")){
                String PretTEMP = LCost.getText();
                double pretTEMP = Double.parseDouble(PretTEMP);
                
                subTotal +=pretTEMP;
                String SubTotal = Double.toString(subTotal);
                SubTotal = String.format("%.02f", subTotal); 
                LSubtotal.setText(SubTotal); 
                
                String NumeProdus = cautaObiecte(CodNumar, "Nume");
                counter++;
                LNume.setText(counter + "x " + NumeProdus);
                String Pret = cautaObiecte(CodNumar, "Pret");
                adaugaLista(NumeProdus, Pret);
            } else { 
                eroare("Produsele la kilogram nu se dubleaza.");
            }
        } else {
            eroare("Nici un cod valabil introdus.");
        }
    }//GEN-LAST:event_LXActionPerformed

    private void R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R6ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R6.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R6ActionPerformed

    private void R7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R7ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R7.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R7ActionPerformed

    private void R8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R8ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R8.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R8ActionPerformed

    private void R9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R9ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R9.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R9ActionPerformed

    private void R0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R0ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R0.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R0ActionPerformed

    private void R00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R00ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R00.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R00ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R1.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R2.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai.");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R3.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R3ActionPerformed

    private void R4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R4ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai.");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R4.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R4ActionPerformed

    private void R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5ActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai.");
            return;
        }
        String EnterNumber  = rNumerar.getText() + R5.getText();
        rNumerar.setText(EnterNumber);
    }//GEN-LAST:event_R5ActionPerformed

    private void rIncaseazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIncaseazaActionPerformed
         if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai.");
            return;
        }
         String Suma = rNumerar.getText();
         String Total = rTotal.getText();
         double total = Double.parseDouble(Total);
         
         int suma = Integer.parseInt(Suma);
                 
         int parteIntreaga = suma / 100 ;
         double parteZecimala = suma % 100;
         double sumaDouble = (double) parteIntreaga + parteZecimala/100;
         Suma = Double.toString(sumaDouble);
         rNumerar.setText(Suma);
         
         if (sumaDouble <= total){  // daca suma data e mai mica ca si totalul
             rNumerar.setText(null);
             total = total - sumaDouble;
             Total = String.format("%.02f", total);
             rTotal.setText(Total);
         } else { // se da rest
             rTotal.setText(null);
             rNumerar.setText(null);
             LNume.setText(null);
             LCost.setText(null);
             LSubtotal.setText(null);
             double rest = sumaDouble - total;
             String Rest = Double.toString(rest);
             Rest = String.format("%.02f", rest); 
             rRest.setText(Rest);
             subTotal = 0 ;
             
             adaugaLista("delete","");
            
         }
    }//GEN-LAST:event_rIncaseazaActionPerformed
    
    private void R10leiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R10leiActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        rNumerar.setText("1000");
    }//GEN-LAST:event_R10leiActionPerformed

    private void R1LeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1LeuActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        rNumerar.setText("100");
    }//GEN-LAST:event_R1LeuActionPerformed

    private void R50leiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R50leiActionPerformed
        if (rTotal.getText().equals(""))
        {
            eroare("Apasati TOTAL intai");
            return;
        }
        rNumerar.setText("5000"); 
    }//GEN-LAST:event_R50leiActionPerformed

    private void LTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTotalButtonActionPerformed
        if (LSubtotal.getText().equals(""))
        {
            eroare("Niciun produs inregistrat");
            return;
        }
        String TotalNr = Double.toString(subTotal);
        TotalNr = String.format("%.02f", subTotal); 
        rTotal.setText(TotalNr);
    }//GEN-LAST:event_LTotalButtonActionPerformed

    private void rCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCActionPerformed
        rNumerar.setText(null);
    }//GEN-LAST:event_rCActionPerformed
  
    private void adaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugaActionPerformed
        String item = jList1.getSelectedValue(); // produs selectat din lista
        Produs[] produse = declaraObiecte(); // preia array-ul de obiecte
        for(int i = 0; i < produse.length; i++){ // compara Nume cu item ca sa preia CodNumar si booleanul buc/kg
            String Nume = getNumeProdus(i);
            if(Nume.equals(item)){
                if (produse[i].esteBuc){
                    CodNumar = produse[i].getCod();
                    adaugaProdus();
                    return;
                } else if (!produse[i].esteBuc && kg != 0 ){
                    CodNumar = produse[i].getCod();
                    adaugaProduskg();
                    return;
                } else { 
                    eroare("Niciun gramaj inregistrat.");
                }
            }
        }

    }//GEN-LAST:event_adaugaActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfataCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfataCasa().setVisible(true);
                
            }    
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LButton0;
    private javax.swing.JButton LButton00;
    private javax.swing.JButton LButton1;
    private javax.swing.JButton LButton2;
    private javax.swing.JButton LButton3;
    private javax.swing.JButton LButton4;
    private javax.swing.JButton LButton5;
    private javax.swing.JButton LButton6;
    private javax.swing.JButton LButton7;
    private javax.swing.JButton LButton8;
    private javax.swing.JButton LButton9;
    private javax.swing.JButton LButtonINM;
    private javax.swing.JButton LButtonInput;
    private javax.swing.JButton LButtonVir;
    private javax.swing.JButton LClear;
    private javax.swing.JTextField LCost;
    private javax.swing.JTextField LNume;
    private javax.swing.JTextField LSubtotal;
    private javax.swing.JButton LTotalButton;
    private javax.swing.JButton LX;
    private javax.swing.JButton R0;
    private javax.swing.JButton R00;
    private javax.swing.JButton R1;
    private javax.swing.JButton R10lei;
    private javax.swing.JButton R1Leu;
    private javax.swing.JButton R2;
    private javax.swing.JButton R3;
    private javax.swing.JButton R4;
    private javax.swing.JButton R5;
    private javax.swing.JButton R50lei;
    private javax.swing.JButton R6;
    private javax.swing.JButton R7;
    private javax.swing.JButton R8;
    private javax.swing.JButton R9;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField TextIntrodus;
    private javax.swing.JButton adauga;
    private javax.swing.JLabel er;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel qw;
    private javax.swing.JButton rC;
    private javax.swing.JButton rIncaseaza;
    private javax.swing.JTextField rNumerar;
    private javax.swing.JTextField rRest;
    private javax.swing.JTextField rTotal;
    private javax.swing.JLabel we;
    // End of variables declaration//GEN-END:variables

}